"""add_active_time_to_offers

Revision ID: 147458278fe6
Revises: 838184a7b707
Create Date: 2026-03-09 07:26:31.979097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '147458278fe6'
down_revision: Union[str, Sequence[str], None] = '838184a7b707'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offers', sa.Column('active_from', sa.String(), nullable=True))
    op.add_column('offers', sa.Column('active_until', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('offers', 'active_until')
    op.drop_column('offers', 'active_from')
    # ### end Alembic commands ###
