"""update_offers_schema

Revision ID: 67364a2f60b2
Revises: 6c96396e4aae
Create Date: 2026-03-08 08:09:25.765265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '67364a2f60b2'
down_revision: Union[str, Sequence[str], None] = '6c96396e4aae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offers', sa.Column('is_flash', sa.Boolean(), nullable=True))
    op.add_column('offers', sa.Column('is_promo', sa.Boolean(), nullable=True))
    op.add_column('offers', sa.Column('flash_start', sa.DateTime(), nullable=True))
    op.add_column('offers', sa.Column('flash_end', sa.DateTime(), nullable=True))
    op.add_column('offers', sa.Column('promo_expiry', sa.DateTime(), nullable=True))
    op.add_column('offers', sa.Column('required_tier', sa.String(), nullable=True))
    op.drop_column('offers', 'required_level')
    op.drop_column('offers', 'offer_type')
    op.drop_column('offers', 'expiry_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offers', sa.Column('expiry_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('offers', sa.Column('offer_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('offers', sa.Column('required_level', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('offers', 'required_tier')
    op.drop_column('offers', 'promo_expiry')
    op.drop_column('offers', 'flash_end')
    op.drop_column('offers', 'flash_start')
    op.drop_column('offers', 'is_promo')
    op.drop_column('offers', 'is_flash')
    # ### end Alembic commands ###
