"""update_models

Revision ID: 6c96396e4aae
Revises: 1bb02fcf1eea
Create Date: 2026-03-07 12:17:19.484699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c96396e4aae'
down_revision: Union[str, Sequence[str], None] = '1bb02fcf1eea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sliders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('slider_type', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('offers', sa.Column('top_image', sa.String(), nullable=True))
    op.add_column('offers', sa.Column('discount', sa.Integer(), nullable=True))
    op.add_column('offers', sa.Column('save_up_to_currency', sa.String(), nullable=True))
    op.add_column('offers', sa.Column('is_top', sa.Boolean(), nullable=True))
    op.add_column('offers', sa.Column('level_priority', sa.Integer(), nullable=True))
    op.add_column('offers', sa.Column('orders', sa.Integer(), nullable=True))
    op.drop_column('offers', 'discount_percentage')
    op.add_column('vendors', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('vendors', sa.Column('profile_image', sa.String(), nullable=True))
    op.add_column('vendors', sa.Column('banner_image', sa.String(), nullable=True))
    op.add_column('vendors', sa.Column('lat', sa.String(), nullable=True))
    op.add_column('vendors', sa.Column('lon', sa.String(), nullable=True))
    op.add_column('vendors', sa.Column('is_top', sa.Boolean(), nullable=True))
    op.add_column('vendors', sa.Column('orders', sa.Integer(), nullable=True))
    op.add_column('vendors', sa.Column('is_pos', sa.Boolean(), nullable=True))
    op.drop_column('vendors', 'logo')
    op.drop_column('vendors', 'cover_image')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendors', sa.Column('cover_image', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('vendors', sa.Column('logo', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('vendors', 'is_pos')
    op.drop_column('vendors', 'orders')
    op.drop_column('vendors', 'is_top')
    op.drop_column('vendors', 'lon')
    op.drop_column('vendors', 'lat')
    op.drop_column('vendors', 'banner_image')
    op.drop_column('vendors', 'profile_image')
    op.drop_column('vendors', 'phone')
    op.add_column('offers', sa.Column('discount_percentage', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True))
    op.drop_column('offers', 'orders')
    op.drop_column('offers', 'level_priority')
    op.drop_column('offers', 'is_top')
    op.drop_column('offers', 'save_up_to_currency')
    op.drop_column('offers', 'discount')
    op.drop_column('offers', 'top_image')
    op.drop_table('sliders')
    # ### end Alembic commands ###
