"""add_image_and_product_id_to_subscription_plans

Revision ID: 838184a7b707
Revises: 67364a2f60b2
Create Date: 2026-03-08 22:47:26.586768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '838184a7b707'
down_revision: Union[str, Sequence[str], None] = '67364a2f60b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscription_plans', sa.Column('duration_months', sa.Integer(), nullable=True))
    op.add_column('subscription_plans', sa.Column('apple_product_id', sa.String(), nullable=True))
    op.add_column('subscription_plans', sa.Column('image', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscription_plans', 'image')
    op.drop_column('subscription_plans', 'apple_product_id')
    op.drop_column('subscription_plans', 'duration_months')
    # ### end Alembic commands ###
